const markets = [
  {question:"Will the Fed cut rates before October?",category:"ECONOMY",market:42,oracle:57,confidence:"High",ev:"+13.7%",action:"BUY YES"},
  {question:"Will Bitcoin exceed $150k this year?",category:"CRYPTO",market:31,oracle:39,confidence:"Medium",ev:"+6.8%",action:"BUY YES"},
  {question:"Will global temperature set a record?",category:"CLIMATE",market:68,oracle:61,confidence:"Medium",ev:"+5.4%",action:"BUY NO"},
];

export default function Home() {
  return <><header><div><p className="eyebrow">PREDICTION MARKET INTELLIGENCE</p><h1>Decision edge, quantified.</h1><p className="subtitle">Bayesian research and disciplined position sizing—not certainty.</p></div><button>Scan markets</button></header><section className="metrics"><article><label>Positive EV markets</label><strong>18</strong><small>Across 247 active markets</small></article><article><label>Average identified edge</label><strong className="green">8.4%</strong><small>After execution costs</small></article><article><label>Forecast Brier score</label><strong>0.142</strong><small className="green">↓ 0.018 this quarter</small></article><article><label>Analysis freshness</label><strong>96%</strong><small>Updated within one hour</small></article></section><section id="markets" className="panel"><div className="panelHead"><div><p className="eyebrow">OPPORTUNITY RADAR</p><h2>Highest expected value</h2></div><span className="live">● LIVE</span></div><div className="table"><div className="row headings"><span>Market</span><span>Market</span><span>Oracle</span><span>Edge / EV</span><span>Confidence</span><span>Action</span></div>{markets.map((m)=><div className="row" key={m.question}><span><b>{m.question}</b><small>{m.category}</small></span><span>{m.market}%</span><span className="oracle">{m.oracle}%</span><span className="green"><b>{m.oracle-m.market>0?"+":""}{m.oracle-m.market} pts</b><small>{m.ev} EV</small></span><span><em className={m.confidence.toLowerCase()}>{m.confidence}</em></span><span><button className={m.action.includes("NO")?"no":"yes"}>{m.action}</button></span></div>)}</div></section><section className="lower"><article id="portfolio" className="panel"><p className="eyebrow">PORTFOLIO</p><h2>Risk at a glance</h2><div className="risk"><strong>$10,000</strong><span>Bankroll</span><strong>$1,240</strong><span>Capital deployed</span><strong>4.1%</strong><span>Maximum drawdown</span></div></article><article id="research" className="panel"><p className="eyebrow">MODEL DISCIPLINE</p><h2>Evidence quality</h2><div className="bar"><span style={{width:"81%"}} /></div><p className="subtitle">81% primary or high-reliability sources. Every conclusion retains citations and counter-evidence.</p></article></section><footer>ORACLE provides probabilistic decision support. It does not guarantee outcomes or execute trades.</footer></>;
}
